services:
  frontend:
    build: .

    restart: unless-stopped

    env_file:
      - .env.local

    environment:
      NEXT_PUBLIC_API_URL: http://ec2-54-169-199-197.ap-southeast-1.compute.amazonaws.com:1337/api
      NODE_ENV: production

    ports:
      - "3000:3000"

    networks:
      - default

networks:
  default:
    driver: bridge
